spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
    platform: h2

  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.yaml

  management:
    endpoints:
      web:
        exposure:
          include: actuator, info, health, metrics
    endpoint:
      health:
        show-details: always
    health:
      diskspace:
        enabled: false
  info:
    storeName: Dunkin Decoctions
  logging:
    level:
      root: INFO